### ISSUE TITLE
[help wanted] nuxt-use-motion demo not work.

### ISSUE THREAD

**Issue by oceanlvr** [Tahul/nuxt-use-motion#2]
This is a cool animation library, and I plan to use this library to build my own animation. When I configure the `nuxt.config.ts` to set an animation just like your example, and do not work.

here is my component:

```vue
<template>
  <div class="container1">
    <div class="block1" v-motion-pop-bottom />
  </div>
</template>

<script lang="ts">
import { defineComponent } from '@nuxtjs/composition-api'
export default defineComponent({
  name: 'test',
  setup() {},
})
</script>
<style>

.container1 {
  width: 400px;
  height: 400px;
  display: flex;
  justify-content: center;
  align-items: center;
  border: 1px solid blue;
}
.block1 {
  width: 50px;
  height: 50px;
  background-color: red;
}
</style>
```

nuxt.config.ts

```ts
{
  motions: {
    // motions Configuration https://motion.vueuse.org/
    directives: {
      'pop-bottom': {
        initial: {
          y: 400,
        },
        enter:{
          y: 0,
          x: 300,
          transition: {
              repeat: Infinity,
              repeatType: 'mirror',
          },
        },  
      }
    }
  }
}
```
It doesn't work:

![image](https://user-images.githubusercontent.com/36698124/108873256-f161e100-7635-11eb-9d20-99e95abab178.png)

here is my environment:

- "nuxt-use-motion": "^1.0.4",
- "nuxt": "^2.14.6",
- "@nuxtjs/composition-api": "^0.17.0",

Looking forward to your reply.

**Comment by Tahul** [comment]
Hello @oceanlvr ;

Could you update do 1.0.5 and tell me if it is working better ?

Also, please note that the configuration key is now "motion" instead of "motions".

Your directive `initial` key should include a value for `x`, or it will not complete a transition on this value but instead set it directly.

Please let me know if you have any more feedback, and don't forget including context like you did, it helps me a lot. 👍

**Comment by Tahul** [comment]
You might need to specify your configs from `app/motion.config.js` if you use 1.0.5.

There seem to be a problem with changes merged here:
https://github.com/Tahul/nuxt-use-motion/pull/3

I'm waiting for an answer from the author of the PR here:
https://github.com/Tahul/nuxt-use-motion/pull/3#issuecomment-784614950

Stay tuned for updates. 👋

**Comment by oceanlvr** [comment]
@Tahul Thanks for your patient. QVQ

I complied with the PR you mentioned with this change:

and it seems import another `"@nuxtjs/composition-api@^0.20.2"` just in my `yarn.lock`:


![image](https://user-images.githubusercontent.com/36698124/108932206-ee8ddd00-7683-11eb-8b7e-12f858b0d818.png)




there is my action:

move `nuxt-use-motion` to devdepen, and update to `1.0.5`

```shell
yarn remove nuxt-use-motion
yarn add --dev nuxt-use-motion
```

update `nuxt.config.ts` file:

```diff
//nuxt.config.ts
+  buildModules: ['nuxt-use-motion']
-  modules: ['nuxt-use-motion']
```

and 

```diff
// nuxt.config.ts
-   motions: {
+  motion: {
```

This is my motions config now:
```ts
{
  buildModules: [
    // https://go.nuxtjs.dev/typescript
    '@nuxt/typescript-build',
    '@nuxtjs/composition-api',
    'nuxt-use-motion',
  ],


// nuxt.config.ts
  motion: {
    // motions Configuration https://motion.vueuse.org/
    directives: {
      'pop-bottom': {
        initial: {
          x: 0,
          y: 400,
        },
        enter:{
          y: 0,
          x: 300,
          transition: {
              repeat: Infinity,
              repeatType: 'mirror',
          },
      },  
    }
  }
}
```

package.json:

```json
{
  "devDependencies": {
    "nuxt-use-motion": "^1.0.5",
  }
}
```


environment:

- "nuxt-use-motion": "^1.0.5",
- "@nuxtjs/composition-api": "^0.17.0",
- "nuxt": "^2.14.6",

**Comment by oceanlvr** [comment]
I think it might be import the `@nuxtjs/composition-api` in the `buildModules`, so I remove the `@nuxtjs/composition-api` in my `nuxt.config.ts`.

```diff
  // Modules for dev and build (recommended) (https://go.nuxtjs.dev/config-modules)
  buildModules: [
    // https://go.nuxtjs.dev/typescript
    '@nuxt/typescript-build',
-    '@nuxtjs/composition-api',
    'nuxt-use-motion',
  ],
```

it is normal again, but animotion still not work:

![image](https://user-images.githubusercontent.com/36698124/108932941-2fd2bc80-7685-11eb-8673-7f8ee9cac1ab.png)

**Comment by praburangki** [comment]
![image](https://user-images.githubusercontent.com/8610935/108934353-be483d80-7687-11eb-9e44-18d38f1a962f.png)

Additional notes that might be helpful.

I also can't make the demo working.

**Comment by ChangJoo-Park** [comment]
Same here 😭

**Comment by ChangJoo-Park** [comment]
I found the solution of working but It is temporarily. Follow the below steps.

```
1. Clone @vueuse/motion on your local `git clone https://github.com/vueuse/motion`
2. In cloned nuxt-use-motion directory, remove this line `"@vueuse/motion": "^1.0.7",`
3. Install  local @vueuse/motion with this command `yarn add file:./../motion`
4. Run demo `yarn dev`
```

I don't know why It is working. latest npm module is same with master at this moment.

**Comment by Tahul** [comment]
> ![image](https://user-images.githubusercontent.com/8610935/108934353-be483d80-7687-11eb-9e44-18d38f1a962f.png)
> 
> Additional notes that might be helpful.
> 
> I also can't make the demo working.

This has been fixed with this: https://github.com/vueuse/motion/commit/6fc09df13a9cd67489c58b9b20a2fe30d8f9c2b6

**Comment by Tahul** [comment]
> I found the solution of working but It is temporarily. Follow the below steps.
> 
> 1. Clone @vueuse/motion on your local `git clone https://github.com/vueuse/motion`
> 2. Run `yarn serve:demo` in motion and terminate it
> 3. In cloned nuxt-use-motion directory, remove this line `"@vueuse/motion": "^1.0.7",`
> 4. Install  local @vueuse/motion with this command `yarn add file:./../motion`
> 5. Run demo `yarn dev`
> 
> I don't know why It is working. latest npm module is same with master at this moment.
> 
> This is my yarn.lock in nuxt-use-motion
> 
> ```
> "@vueuse/motion@file:./../motion":
>   version "1.0.7"
>   dependencies:
>     "@vueuse/core" "^4.2.1"
>     popmotion "^9.2.1"
>     vue-demi latest
>   optionalDependencies:
>     "@vue/composition-api" "^1.0.0-rc.2"
> ```

Please try version 1.0.8 of nuxt-use-motion, that should resolve this problem.

I tried to install it myself on your repo, following the current readme, and it worked!

**Comment by ChangJoo-Park** [comment]
> Please try version 1.0.8 of nuxt-use-motion, that should resolve this problem.
> 
> I tried to install it myself on your repo, following the current readme, and it worked!

Thanks @Tahul , I follow the README.md. There is no error about RefImpl, but not working. stay still my div with @vueuse/motion directives. 

I set motion config in nuxt.config.js

https://github.com/ChangJoo-Park/nuxt-use-motion-issue-01/blob/main/nuxt.config.js#L42-L57

```html
      <div v-motion-pop-bottom>Pop from bottom! 🎺</div>
```
it rendered below. 😭  not working

```html
<div style="transform: translateZ(0px);">Pop from bottom! 🎺</div>
```

**Comment by Tahul** [comment]
Hello everyone ;

As it might be closely related, I suggest you to follow the evolution of this issue:
https://github.com/vueuse/motion/issues/8

I'm currently working on the Vue 2 support, and will be receiving help from other developers concerning that task.

The strange behaviors I'm experiencing with Nuxt might be closely related to the Vue 2 support.

I'm currently waiting for feedback concerning those issues, and will keep you posted about this.

Sorry for the inconvenience, I hope to fix it soon!

🙌

**Comment by Tahul** [comment]
@ChangJoo-Park, @oceanlvr ;

Could you confirm that the current version is working on your side so I can close this issue ?

https://codesandbox.io/s/nuxt-use-motion-issue-reproduction-mhwy9?file=/components/Logo.vue

As you can see here, it is actually working with Nuxt on my side.

Please let me know if you still have any issue.

**Comment by ChangJoo-Park** [comment]
Thank you @Tahul  I check your codesandbox and [my repo](https://github.com/ChangJoo-Park/nuxt-use-motion-issue-01/). Everything is OK 🎉

**Comment by oceanlvr** [comment]
@Tahul Thanks for your great work, it also works for my website. 🚀 🚀
