### ISSUE TITLE
how to used nuxt person.vue demo ?

### ISSUE THREAD

**Issue by productfrontenddeveloper** [Tahul/nuxt-use-motion#5]
https://codesandbox.io/s/vueusemotion-me1jn?file=/src/components/Person.vue:80-94

how to nuxt used ? 
![Screen Shot 2021-03-04 at 10 13 44](https://user-images.githubusercontent.com/38668796/109925071-4e166900-7cd2-11eb-94ac-f760ca718ea2.png)
<img width="633" alt="Screen Shot 2021-03-04 at 10 13 57" src="https://user-images.githubusercontent.com/38668796/109925093-566ea400-7cd2-11eb-8269-4a7cf194d2b3.png">

**Comment by oceanlvr** [comment]
@productfrontenddeveloper  this issue may help you -> https://github.com/Tahul/nuxt-use-motion/issues/2

**Comment by oceanlvr** [comment]
https://codesandbox.io/s/nuxt-use-motion-issue-reproduction-mhwy9?file=/components/Logo.vue
